Repository wecode-bootcamp-korea/23-2nd-MAEILYHOTEL-frontend, pull requests merged in 2021-08, with the labels that each got.

#2 [23기 김동우] [ADD] : Nav Layout
  public/images/image.txt
  public/images/logo.png
  public/index.html
  src/Routes.js
  src/component/Footer.js
  src/component/Nav.js
  src/component/Nav/Icon.js
  src/component/Nav/Nav.js
  src/pages/Main/ImageSlider/ImageSlider.js
  src/pages/Main/ListFilter/ListFilter.js
  src/styles/Mixins.js
Labels: Status: 리뷰 요청

#1 [23기 김동우] [ADD] : Main / Search Page Layout
  public/images/Main/MainBackGroundImg.jpg
  src/pages/Main/Main.js
  src/pages/Main/MainSearch/MainSearchForm.js
  src/pages/Main/MainSearch/MainSearchLabel.js
  src/pages/Main/MainSearch/MainWrapper.js
Labels: Status: Accepted

#4 [23기 김명성] ADD : 상세 페이지 레이아웃 작성
  public/data/HOTEL_DATA.json
  public/images/comment_logo.png
  public/images/hotel_1.jpg
  public/images/map_background.jpg
  public/images/parking_icon.png
  public/images/restaurant_icon.png
  public/images/wifi_icon.png
  src/component/Nav/Nav.js
  src/pages/Detail/Detail.js
  src/pages/Detail/DetailHotelFacility/DetailHotelFacility.js
  src/pages/Detail/DetailHotelImage/DetailHotelImage.js
  src/pages/Detail/DetailHotelInfo/DetailHotelInfo.js
  src/pages/Detail/DetailHotelInfo/INFO_LIST.js
  src/pages/Detail/DetailHotelInfo/InfoList.js
  src/pages/Detail/DetailHotelMap/DetailHotelMap.js
  src/pages/Detail/DetailHotelRoom/DetailHotelRoom.js
  src/pages/Detail/DetailHotelTitle/DetailHotelTitle.js
  src/pages/Detail/DetailHotelTitle/DownloadCoupon/DownloadCoupon.js
  src/pages/Detail/DetailHotelUsingHour/DetailHotelUsingHour.js
  src/styles/Mixins.js
Labels: Status: Accepted

#5 [23기 김동우] [ADD] nav Login 기능 / Redirect page / fetch hooks 작성
  .gitignore
  public/images/Nav/LoginButton.png
  public/images/Redirect/Loading.png
  public/images/Redirect/Loading2.png
  src/Routes.js
  src/component/Nav/Icon.js
  src/component/Nav/Login.js
  src/component/Nav/Nav.js
  src/config.js
  src/hooks.js
  src/pages/Redirect/KakaoLoginLogic.js
  src/pages/Redirect/Redirect.js
  src/styles/theme.js
Labels: Status: 수정 요청

#6 [23기 김명성] ADD : 지도 기능 구현 / MODIFY : 상세 페이지 데이터 재구성
  package-lock.json
  package.json
  public/data/HOTEL_DATA.json
  public/data/ROOM_DATA.json
  public/images/hotel_1.jpg
  public/images/parking_icon.png
  public/images/restaurant_icon.png
  public/images/wifi_icon.png
  src/component/Detail/DetailCommon.js
  src/component/Detail/DetailHotelImage/DetailHotelImage.js
  src/component/Detail/DetailHotelUsingHour/DetailHotelUsingHour.js
  src/component/Detail/DetailHotelUsingHour/TimeInfo.js
  src/config.js
  src/pages/Detail/Detail.js
  src/pages/Detail/DetailHotelFacility/DetailHotelFacility.js
  src/pages/Detail/DetailHotelFacility/FacilitiesIconWrap.js
  src/pages/Detail/DetailHotelImage/DetailHotelImage.js
  src/pages/Detail/DetailHotelInfo/DetailHotelInfo.js
  src/pages/Detail/DetailHotelInfo/INFO_LIST.js
  src/pages/Detail/DetailHotelInfo/InfoList.js
  src/pages/Detail/DetailHotelMap/AddressBox.js
  src/pages/Detail/DetailHotelMap/DetailHotelMap.js
  src/pages/Detail/DetailHotelRoom/DetailHotelRoom.js
  src/pages/Detail/DetailHotelRoom/RoomType.js
  src/pages/Detail/DetailHotelTitle/DetailHotelTitle.js
  src/pages/Detail/DetailHotelTitle/DownloadCoupon.js
  src/pages/Detail/DetailHotelUsingHour/DetailHotelUsingHour.js
  src/pages/Detail/MapModal.js
Labels: Status: 리뷰 요청

#8 [23기 김명성] ADD : 객실 필터 기능 구현
  public/data/HOTEL_DATA.json
  src/config.js
  src/pages/Detail/Detail.js
  src/pages/Detail/DetailHotelRoom/DetailHotelRoom.js
  src/pages/Detail/DetailHotelRoom/RoomType.js
  src/pages/Detail/DetailHotelTitle/DetailHotelTitle.js
  src/pages/Detail/MapModal.js
Labels: Status: 리뷰 요청

#7 [23기 김동우] [ADD] : Location Modal, Calendar layout&logic / Main SearchForm logic
  .gitignore
  package-lock.json
  package.json
  public/data/CALENDAR.json
  src/component/Calendar/Calendar.js
  src/component/Calendar/CalendarLogic.js
  src/component/Calendar/CalendarWrapper.js
  src/component/Calendar/NextLink.js
  src/component/Nav/IconsWrapper.js
  src/component/Nav/LoginButton.js
  src/component/Nav/Nav.js
  src/config.js
  src/hooks.js
  src/pages/Detail/Detail.js
  src/pages/Detail/DetailHotelRoom/DetailHotelRoom.js
  src/pages/Main/LocationModal/LocationList/City.js
  src/pages/Main/LocationModal/LocationList/CityListWrap.js
  src/pages/Main/LocationModal/LocationList/LOCATION_LIST.js
  src/pages/Main/LocationModal/LocationList/LocationList.js
  src/pages/Main/LocationModal/LocationList/Region.js
  src/pages/Main/LocationModal/LocationList/RegionListWrap.js
  src/pages/Main/LocationModal/LocationListTabTitle.js
  src/pages/Main/LocationModal/LocationListTitle.js
  src/pages/Main/LocationModal/LocationModal.js
  src/pages/Main/Main.js
  src/pages/Main/MainSearch/MainSearchForm.js
  src/pages/Main/MainSearch/MainSearchLabel.js
  src/pages/Main/MainSearch/MainWrapper.js
  src/pages/Main/MainSearch/SearchLocationModal.js
  src/pages/Redirect/KakaoLoginLogic.js
  src/pages/Redirect/Redirect.js
  src/styles/GlobalStyles.js
  src/styles/theme.js
Labels: Status: 리뷰 요청

#9 [23기 문주영] nav 모달 레이아웃 및 회원등급 - conflict 해결완료입니다.
  package-lock.json
  src/Routes.js
  src/component/Nav/IconsWrapper.js
  src/component/Nav/Nav.js
  src/component/Nav/NavModal.js
  src/config.js
  src/pages/List/HotelList.js
  src/pages/List/List.js
  src/styles/GlobalStyles.js
Labels: Status: 리뷰 요청
